name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.0.9
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  simple_gesture_detector: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter